[package]
name = "sprite_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core = { path = "../../packages/core" }
shared = { path = "../../packages/shared" }
bevy = { workspace = true }
